### PR TITLE
Fixed IT test, added docker config, spelling and codestyle

### PR DESCRIPTION
**Pull request by Graceas**
- codestyle
- spelling
- changed docker port "expose" for network (6863 -> 6870)
- added possibility for change dockerIpAddress (remove "localhost" hardcode)
- removed unused dependency
- changed default port in the Peers Database class (6863 -> 6870)
- added connection information to the "connect" API method
- fixed WideStateGenerationSuite it test (increase await time and max-queue-size)
- added mode-it/printTests command, for dumping test classes name
- added chainId = I to check application name (according to settings)
- fixed connect method test
- update readme

### CODE REVIEW

**Comment by Graceas** [comment]
I missed checking that the channel was created in a previous pull request. Also fixed test.

**Comment by deadblackclover** [comment]
Thanks for PR! In file `node/src/main/scala/com/acrylplatform/settings/NetworkSettings.scala` you added a new parameter `dockerIpAddress`, but used the condition to rule out errors. In order not to use the condition, there is a special file `node/src/main/resources/application.conf` in which there are all the parameters and their default values. This file is put into the jar automatically and all parameters can be overwritten through an external config.

`node-it/src/test/scala/com/acrylplatform/it/Docker.scala` the use of `dockerIpAddress` is not entirely clear. Since this is an integration test, there will always be `localhost`, no longer where it is used. So we think this is not rational.

**Comment by Graceas** [comment]
Ok. I missed it.

About dockerIpAddress, I have used external docker machine, so it's required for me. But if you think is not useful case, it's ok.

Generally, is everything okay? I can remove this option and create a new pull request. What do you think?

**Comment by deadblackclover** [comment]
Yes, everything is good! Let's leave `dockerIpAddress` and set the default value in `node/src/main/resources/application.conf`. I think the presence of such a parameter would not want.

**Comment by Graceas** [comment]
ok

**Pull request closed without merging**
